version: '3'
services:
  # 
  # Client
  # 
  client:
    build: .
    image: von-base
    command: 'bash -c ''./scripts/start_client.sh'''
    networks:
      - von

  # 
  # Webserver
  # 
  webserver:
    build: .
    image: von-base
    command: 'bash -c ''./scripts/start_webserver.sh'''
    environment:
      - IP=${IP}
      - IPS=${IPS}
    networks:
      - von
    ports:
      - 8000:8000
    volumes:
      - ./.mnt:/home/indy/.mnt

  # 
  # Nodes
  # 
  node1:
    build: .
    image: von-base
    command: 'bash -c ''./scripts/start_node.sh 1'''
    networks:
      - von
    ports:
      - 9701:9701
      - 9702:9702
    environment:
      - IP=${IP}
      - IPS=${IPS}
    volumes:
      - ./.mnt/node1:/var/lib/indy
    
  node2:
    build: .
    image: von-base
    command: 'bash -c ''./scripts/start_node.sh 2'''
    networks:
      - von
    ports:
      - 9703:9703
      - 9704:9704
    environment:
      - IP=${IP}
      - IPS=${IPS}
    volumes:
      - ./.mnt/node2:/var/lib/indy

  node3:
    build: .
    image: von-base
    command: 'bash -c ''./scripts/start_node.sh 3'''
    networks:
      - von
    ports:
      - 9705:9705
      - 9706:9706
    environment:
      - IP=${IP}
      - IPS=${IPS}
    volumes:
      - ./.mnt/node3:/var/lib/indy
    
  node4:
    build: .
    image: von-base
    command: 'bash -c ''./scripts/start_node.sh 4'''
    networks:
      - von
    ports:
      - 9707:9707
      - 9708:9708
    environment:
      - IP=${IP}
      - IPS=${IPS}
    volumes:
      - ./.mnt/node4:/var/lib/indy

networks:
  von: